//create user
POST http://localhost:5000/users 
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@gmail.com",
    "password": "12345678",
    "confPassword": "12345678",
    "role": "admin"
}


###
//get all users
GET http://localhost:5000/users

###
//get user by id
GET http://localhost:5000/users/cbe79fcd-71e9-40e3-b144-681c154662e7

###
//update user
PATCH  http://localhost:5000/users/f9743112-12ad-4f1b-a30e-c545c13bc289
Content-Type: application/json

{
    "name": "Adam ",
    "email": "adam@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"
}

###
//delete user
DELETE  http://localhost:5000/users/fc02af36-67ca-47dd-9f9e-4e7a574fbb28

###
//login admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "12345678"
}

###
//login user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "adamnur@gmail.com",
    "password": "12345678"
}

###
//get user by token
GET http://localhost:5000/me

###
//logout user
DELETE http://localhost:5000/logout



###
//Get all products
GET http://localhost:5000/product

###
//Get single products
GET http://localhost:5000/product/7fdc580e-ae43-49eb-8e54-292fa692d227


###
//Post product
POST http://localhost:5000/product
Content-Type: application/json

{
    "name": "tes6",
    "price": "234"
}

###